default: &default
  adapter: mysql2
  encoding: utf8
  database: locamail
  host: db
  username: root
  password: pass
  reconnect: true
  pool: 15

development:
  <<: *default

test:
  <<: *default
  pool: 15
  database: sro_test
  username: root
  password: root

production:
  <<: *default
